CREATE TABLE Address
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country     VARCHAR(255),
    city        VARCHAR(255),
    street      VARCHAR(255),
    buildingNum INTEGER                                  NOT NULL,
    flatNum     INTEGER                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE Person
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    age        INTEGER                                  NOT NULL,
    email      VARCHAR(255),
    address_id INTEGER,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

ALTER TABLE Person
    ADD CONSTRAINT FK_PERSON_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES Address (id);